export const products = [
    {
        id: 1357188438,
        title: "Rebellen-Manifest (Notizbuch)",
        description: "Protokolliere deine revolutionären Bildungsideen - inklusive Geheimfach für Spickzettel!",
        imageUrl: "/merchImages/book/spiral-notebook-white-front-67ed206d331bb.jpg",
        price: 24.99,
        salePrice: 17.99,
        tag: "Bestseller",
    },
    {
        id: 2357188438,
        title: "Systemsprenger-Hoodie",
        description: "100% Baumwolle, 200% Bildungsprotest. Trag ihn zum nächsten Elternsprechtag!",
        imageUrl: "/merchImages/pullover/premium-eco-hoodie-black-front-67ed35dd2fc2d.png",
        price: 39.99,
        salePrice: 29.99,
        tag: "Neuheit",
    },
    {
        id: 2747018438,
        title: "Aufstand-Stecknadeln (Set)",
        description: "6 rebellische Motive: Von 'Noten abschaffen' bis 'Pausen verlängern'",
        imageUrl: "/merchImages/stifte/set-of-pin-buttons-white-1.25-front-67ed2a72ae151.png",
        price: 12.99,
        salePrice: 9.99,
        tag: "Limitierter Vorrat",
    },
    {
        id: 3747018438,
        title: "Lehrer-Schock-Tasse",
        description: "Hält deinen Kaffee heiß und deine Meinung heißer. Motiv: 'Mein anderer Becher ist ein Abschlusszeugnis'",
        imageUrl: "/merchImages/tasse/white-glossy-mug-white-11-oz-handle-on-left-67ed2419ed924.png",
        price: 19.99,
        salePrice: 14.99,
        tag: "Witzig",
    },
    {
        id: 4747018438,
        title: "Pausenlänge-Rechner (Trinkflasche)",
        description: "1L Volumen = 1 Stunden Matheunterricht überleben. Mit Geheimfach für Schokoriegel!",
        imageUrl: "/merchImages/trinkflasche/stainless-steel-water-bottle-with-a-straw-lid-white-32-oz-front-67ed2679e6985.png",
        price: 29.99,
        salePrice: 24.99,
        tag: "Praktisch",
    },
    {
        id: 5747018438,
        title: "Schulstreik-T-Shirt",
        description: "100% Bio-Baumwolle, 0% Hausaufgaben. Motiv: 'Ich bin hier freiwillig... sagte nie jemand'",
        imageUrl: "/merchImages/tshirt/mens-premium-cotton-t-shirt-black-front-67ed4d115062d.png",
        price: 27.99,
        salePrice: 22.99,
        tag: "Neuheit",
    }
];